### PR TITLE
Electron: Added Context Menu to Text Fields

### PR DESCRIPTION
**Pull request by redlion-github**
Addresses issue #13

### CODE REVIEW

**Comment by paulshapiro** [comment]
Hey RedLion ! Thanks for submitting this PR. One issue I see here though is that RootView.web.js must remain platform agnostic - but your commit adds an electron-only dependency.

**Comment by redlion-github** [comment]
Right, I'll take another look at that. Thanks.

**Comment by redlion-github** [comment]
I moved the code to the electron renderer. Let me know if there are any other issues.

**Comment by paulshapiro** [comment]
Ok, so that's a better location. Couple remaining things…

* I noticed that this enables a right click contextual menu to be opened on a variety of other elements… most primarily links, which exposes the ability to copy the link… which is meaningless/undefined, leading to incorrect UX, yadda yadda yadda.. :) Is there any way we can constrain the contextual menu to only the text fields in `MMAppUICommonComponents`, such as the textarea inputs in `forms.web.js`?

* Can we remove the extra commented code 

```
/*prepend: (params) => [{
		label: 'Extra Monero Label'
	}],
	labels: { //configure labels here
	copy: 'Copy Address',
	paste: 'Paste Address'
},*/
``` ?

Thanks

**Comment by paulshapiro** [comment]
Just as a general guideline btw we've aimed to make the Electron app virtually unable to be recognized as a web app. That's the goal at least!

**Comment by redlion-github** [comment]
I cleaned up the code. The context menu can be restricted to certain elements, but after testing it, I couldn't find an incidence where it shouldn't be present but was. Can you point me to where you're talking about?

**Comment by paulshapiro** [comment]
As mentioned, there are lots of cases of buttons and links being able to be usd to produce an out of place contextual menu.

**Comment by redlion-github** [comment]
Okay found them, thanks.

**Comment by paulshapiro** [comment]
For future reference I should figure out how to make sure this gets merged to `develop` before `master`.

**Comment by redlion-github** [comment]
Great! No problem.

Yeah. I tried to submit it to develop but it ended up on master. I'll look into it on my side for next time.

**Pull request merged**
