### PR TITLE
'requestee' => first name in request memo heading 

### LINKED ISSUE #126: Change 'Requestee' to contact's (first) name when contact available

### PR DESCRIPTION
**Pull request by fearghasmr**
fixes #126

### CODE REVIEW

**Comment by paulshapiro** [comment]
Nice. But is that [0] access guaranteed to never throw?

**Comment by 2Day4Real** [comment]
Hmm maybe not this is the question that will be take little bit more than just a few words instantly in my head with early hours in the morning...

**Comment by paulshapiro** [comment]
@2Day4Real i dont know why i didnt see a notification of your reply. 

What i'm saying is that the request's `from_fullname` value may be an empty string - in which case the array returned by a .split("") called on it may be empty, meaning a [0] access would not work.

**Review by Psyruss — APPROVED** [review]

**Comment by karlbuys** [comment]
Hi @fearghasmr 

Thank you for the contribution. I know this is long after the fact, but I've looked at whether or not it's feasible to merge this. Unfortunately, some of the refactoring that has been done since then causes it to throw a type error.

You're welcome to resubmit this. from_fullname is guaranteed to return an empty string when the contact name is left blank, so I would suggest doing a check on the length of it. 

I'd be happy to look at merging a PR where this is tweaked to work with the current development branch, if you're still interested

**Pull request closed without merging**
