### PR TITLE
Add note about relative privacy

### PR DESCRIPTION
**Pull request by SamsungGalaxyPlayer**
Add note about relative privacy of lightweight wallets

### CODE REVIEW

**Comment by paulshapiro** [comment]
1. I dont think this is the appropriate location for this note because it's the instructions for how to secure your wallet

2. The number of items on this page (length of text) has been carefully edited to keep the length under the scroll limit so the checkbox remains available.

3. I could definitely see adding a note like this on the features section of our website and/or in our support articles (which will soon be more visible).

Hope that makes sense as a reason to close this. thanks.

**Comment by SamsungGalaxyPlayer** [comment]
@paulshapiro I'm torn; the last recommendation for security provides a similar type of warning.

**Comment by paulshapiro** [comment]
I think we could probably find a way to add the lightwallet server comment to the last item as you note. But remember that people are only finding out about mymonero without other introduction (such as our landing page) by people in the community, etc. Our site makes it clear there's a server in the way and that you can run your own. So a hint here would suffice. I'll make an issue or add it.

**Comment by paulshapiro** [comment]
Just a heads up - this is where I landed on this: 

https://github.com/mymonero/mymonero-app-js/commit/98604c090e2df97c09b8ed13e87e2d590e8b5dc9

https://github.com/mymonero/mymonero-app-ios/commit/56bfd1b1084154a5180d70157e964be15773e30b

Thanks for your suggestions, @SamsungGalaxyPlayer!!

**Pull request closed without merging**
